name: Send GET API Every 5 Minutes

on:
  schedule:
    - cron: '0/5 * * * *'  # Runs at 2:30, 7:30, 12:30, etc. (UTC)
  workflow_dispatch:        # Optional: allows manual trigger

jobs:
  send-get-request:
    runs-on: ubuntu-latest

    steps:
      - name: Send Request
        run: |
          curl -X GET "https://x-store-w2wn.onrender.com/"
